// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import java.lang.String;

privileged aspect Chong20Mobile_Roo_ToString {
    
    public String Chong20Mobile.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Mobileid: ").append(getMobileid()).append(", ");
        sb.append("Userno: ").append(getUserno());
        return sb.toString();
    }
    
}
