// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;

privileged aspect OldUser_Roo_JavaBean {
    
    public String OldUser.getUserno() {
        return this.userno;
    }
    
    public void OldUser.setUserno(String userno) {
        this.userno = userno;
    }
    
    public Integer OldUser.getState() {
        return this.state;
    }
    
    public void OldUser.setState(Integer state) {
        this.state = state;
    }
    
    public Date OldUser.getModifyTime() {
        return this.modifyTime;
    }
    
    public void OldUser.setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
    
    public Boolean OldUser.getHasJoin() {
        return this.hasJoin;
    }
    
    public void OldUser.setHasJoin(Boolean hasJoin) {
        this.hasJoin = hasJoin;
    }
    
}
