// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import com.ruyicai.actioncenter.domain.OldUser;
import java.lang.String;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OldUser_Roo_Entity {
    
    declare @type: OldUser: @Entity;
    
    declare @type: OldUser: @Table(name = "OldUser");
    
    @PersistenceContext
    transient EntityManager OldUser.entityManager;
    
    @Transactional
    public void OldUser.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void OldUser.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            OldUser attached = OldUser.findOldUser(this.userno);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void OldUser.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void OldUser.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public OldUser OldUser.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        OldUser merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager OldUser.entityManager() {
        EntityManager em = new OldUser().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long OldUser.countOldUsers() {
        return entityManager().createQuery("SELECT COUNT(o) FROM OldUser o", Long.class).getSingleResult();
    }
    
    public static List<OldUser> OldUser.findAllOldUsers() {
        return entityManager().createQuery("SELECT o FROM OldUser o", OldUser.class).getResultList();
    }
    
    public static OldUser OldUser.findOldUser(String userno) {
        if (userno == null || userno.length() == 0) return null;
        return entityManager().find(OldUser.class, userno);
    }
    
    public static List<OldUser> OldUser.findOldUserEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM OldUser o", OldUser.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
