// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import java.lang.Integer;
import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect SendMoneyDetails_Roo_JavaBean {
    
    public String SendMoneyDetails.getId() {
        return this.id;
    }
    
    public void SendMoneyDetails.setId(String id) {
        this.id = id;
    }
    
    public String SendMoneyDetails.getSendusername() {
        return this.sendusername;
    }
    
    public void SendMoneyDetails.setSendusername(String sendusername) {
        this.sendusername = sendusername;
    }
    
    public String SendMoneyDetails.getReciverUserno() {
        return this.reciverUserno;
    }
    
    public void SendMoneyDetails.setReciverUserno(String reciverUserno) {
        this.reciverUserno = reciverUserno;
    }
    
    public String SendMoneyDetails.getContent() {
        return this.content;
    }
    
    public void SendMoneyDetails.setContent(String content) {
        this.content = content;
    }
    
    public BigDecimal SendMoneyDetails.getAmt() {
        return this.amt;
    }
    
    public void SendMoneyDetails.setAmt(BigDecimal amt) {
        this.amt = amt;
    }
    
    public Date SendMoneyDetails.getReciveTime() {
        return this.reciveTime;
    }
    
    public void SendMoneyDetails.setReciveTime(Date reciveTime) {
        this.reciveTime = reciveTime;
    }
    
    public Date SendMoneyDetails.getCreateTime() {
        return this.createTime;
    }
    
    public void SendMoneyDetails.setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    public Integer SendMoneyDetails.getReciveState() {
        return this.reciveState;
    }
    
    public void SendMoneyDetails.setReciveState(Integer reciveState) {
        this.reciveState = reciveState;
    }
    
}
