// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import com.ruyicai.actioncenter.domain.SendMoneyDetails;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect SendMoneyDetails_Roo_Json {
    
    public String SendMoneyDetails.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static SendMoneyDetails SendMoneyDetails.fromJsonToSendMoneyDetails(String json) {
        return new JSONDeserializer<SendMoneyDetails>().use(null, SendMoneyDetails.class).deserialize(json);
    }
    
    public static String SendMoneyDetails.toJsonArray(Collection<SendMoneyDetails> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<SendMoneyDetails> SendMoneyDetails.fromJsonArrayToSendMoneyDetailses(String json) {
        return new JSONDeserializer<List<SendMoneyDetails>>().use(null, ArrayList.class).use("values", SendMoneyDetails.class).deserialize(json);
    }
    
}
