// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import com.ruyicai.actioncenter.domain.SSCPrizedDetail;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect SSCPrizedDetail_Roo_Json {
    
    public String SSCPrizedDetail.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static SSCPrizedDetail SSCPrizedDetail.fromJsonToSSCPrizedDetail(String json) {
        return new JSONDeserializer<SSCPrizedDetail>().use(null, SSCPrizedDetail.class).deserialize(json);
    }
    
    public static String SSCPrizedDetail.toJsonArray(Collection<SSCPrizedDetail> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<SSCPrizedDetail> SSCPrizedDetail.fromJsonArrayToSSCPrizedDetails(String json) {
        return new JSONDeserializer<List<SSCPrizedDetail>>().use(null, ArrayList.class).use("values", SSCPrizedDetail.class).deserialize(json);
    }
    
}
