// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import com.ruyicai.actioncenter.domain.SSCPrizedDetailPK;
import java.math.BigDecimal;

privileged aspect SSCPrizedDetail_Roo_JavaBean {
    
    public SSCPrizedDetailPK SSCPrizedDetail.getId() {
        return this.id;
    }
    
    public void SSCPrizedDetail.setId(SSCPrizedDetailPK id) {
        this.id = id;
    }
    
    public BigDecimal SSCPrizedDetail.getTotalPrizeAmt() {
        return this.totalPrizeAmt;
    }
    
    public void SSCPrizedDetail.setTotalPrizeAmt(BigDecimal totalPrizeAmt) {
        this.totalPrizeAmt = totalPrizeAmt;
    }
    
}
