// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import com.ruyicai.actioncenter.domain.SuningRegister;
import java.lang.String;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SuningRegister_Roo_Entity {
    
    declare @type: SuningRegister: @Entity;
    
    declare @type: SuningRegister: @Table(name = "SUNINGREGISTER");
    
    @PersistenceContext
    transient EntityManager SuningRegister.entityManager;
    
    @Transactional
    public void SuningRegister.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void SuningRegister.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            SuningRegister attached = SuningRegister.findSuningRegister(this.mobileid);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void SuningRegister.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void SuningRegister.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public SuningRegister SuningRegister.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        SuningRegister merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager SuningRegister.entityManager() {
        EntityManager em = new SuningRegister().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long SuningRegister.countSuningRegisters() {
        return entityManager().createQuery("SELECT COUNT(o) FROM SuningRegister o", Long.class).getSingleResult();
    }
    
    public static List<SuningRegister> SuningRegister.findAllSuningRegisters() {
        return entityManager().createQuery("SELECT o FROM SuningRegister o", SuningRegister.class).getResultList();
    }
    
    public static SuningRegister SuningRegister.findSuningRegister(String mobileid) {
        if (mobileid == null || mobileid.length() == 0) return null;
        return entityManager().find(SuningRegister.class, mobileid);
    }
    
    public static List<SuningRegister> SuningRegister.findSuningRegisterEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM SuningRegister o", SuningRegister.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
