// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import java.lang.Integer;
import java.lang.String;
import java.util.Date;

privileged aspect Tactivity_Roo_JavaBean {
    
    public String Tactivity.getLotno() {
        return this.lotno;
    }
    
    public void Tactivity.setLotno(String lotno) {
        this.lotno = lotno;
    }
    
    public String Tactivity.getPlaytype() {
        return this.playtype;
    }
    
    public void Tactivity.setPlaytype(String playtype) {
        this.playtype = playtype;
    }
    
    public String Tactivity.getSubChannel() {
        return this.subChannel;
    }
    
    public void Tactivity.setSubChannel(String subChannel) {
        this.subChannel = subChannel;
    }
    
    public String Tactivity.getChannel() {
        return this.channel;
    }
    
    public void Tactivity.setChannel(String channel) {
        this.channel = channel;
    }
    
    public Integer Tactivity.getActivityType() {
        return this.activityType;
    }
    
    public void Tactivity.setActivityType(Integer activityType) {
        this.activityType = activityType;
    }
    
    public String Tactivity.getMemo() {
        return this.memo;
    }
    
    public void Tactivity.setMemo(String memo) {
        this.memo = memo;
    }
    
    public String Tactivity.getExpress() {
        return this.express;
    }
    
    public void Tactivity.setExpress(String express) {
        this.express = express;
    }
    
    public Integer Tactivity.getState() {
        return this.state;
    }
    
    public void Tactivity.setState(Integer state) {
        this.state = state;
    }
    
    public Date Tactivity.getCreateTime() {
        return this.createTime;
    }
    
    public void Tactivity.setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    public Date Tactivity.getLastmodifyTime() {
        return this.lastmodifyTime;
    }
    
    public void Tactivity.setLastmodifyTime(Date lastmodifyTime) {
        this.lastmodifyTime = lastmodifyTime;
    }
    
}
