// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import com.ruyicai.actioncenter.domain.Tactivity;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tactivity_Roo_Entity {
    
    declare @type: Tactivity: @Entity;
    
    declare @type: Tactivity: @Table(name = "TACTIVITY");
    
    @PersistenceContext
    transient EntityManager Tactivity.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Tactivity.id;
    
    public Long Tactivity.getId() {
        return this.id;
    }
    
    public void Tactivity.setId(Long id) {
        this.id = id;
    }
    
    @Transactional
    public void Tactivity.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tactivity.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tactivity attached = Tactivity.findTactivity(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tactivity.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tactivity.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tactivity Tactivity.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tactivity merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tactivity.entityManager() {
        EntityManager em = new Tactivity().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tactivity.countTactivitys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tactivity o", Long.class).getSingleResult();
    }
    
    public static List<Tactivity> Tactivity.findAllTactivitys() {
        return entityManager().createQuery("SELECT o FROM Tactivity o", Tactivity.class).getResultList();
    }
    
    public static Tactivity Tactivity.findTactivity(Long id) {
        if (id == null) return null;
        return entityManager().find(Tactivity.class, id);
    }
    
    public static List<Tactivity> Tactivity.findTactivityEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tactivity o", Tactivity.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
