// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect TaddNumActivity_Roo_JavaBean {
    
    public String TaddNumActivity.getUserno() {
        return this.userno;
    }
    
    public void TaddNumActivity.setUserno(String userno) {
        this.userno = userno;
    }
    
    public String TaddNumActivity.getFlowno() {
        return this.flowno;
    }
    
    public void TaddNumActivity.setFlowno(String flowno) {
        this.flowno = flowno;
    }
    
    public Date TaddNumActivity.getCreateTime() {
        return this.createTime;
    }
    
    public void TaddNumActivity.setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    public Date TaddNumActivity.getModifyTime() {
        return this.modifyTime;
    }
    
    public void TaddNumActivity.setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
    
    public BigDecimal TaddNumActivity.getAddNumState() {
        return this.addNumState;
    }
    
    public void TaddNumActivity.setAddNumState(BigDecimal addNumState) {
        this.addNumState = addNumState;
    }
    
    public String TaddNumActivity.getParams() {
        return this.params;
    }
    
    public void TaddNumActivity.setParams(String params) {
        this.params = params;
    }
    
}
