// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import java.lang.String;

privileged aspect TaddNumActivity_Roo_ToString {
    
    public String TaddNumActivity.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("AddNumState: ").append(getAddNumState()).append(", ");
        sb.append("CreateTime: ").append(getCreateTime()).append(", ");
        sb.append("Flowno: ").append(getFlowno()).append(", ");
        sb.append("ModifyTime: ").append(getModifyTime()).append(", ");
        sb.append("Params: ").append(getParams()).append(", ");
        sb.append("Userno: ").append(getUserno());
        return sb.toString();
    }
    
}
