// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import com.ruyicai.actioncenter.domain.Tagent;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tagent_Roo_Entity {
    
    declare @type: Tagent: @Entity;
    
    declare @type: Tagent: @Table(name = "TAGENT");
    
    @PersistenceContext
    transient EntityManager Tagent.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Tagent.id;
    
    public Long Tagent.getId() {
        return this.id;
    }
    
    public void Tagent.setId(Long id) {
        this.id = id;
    }
    
    @Transactional
    public void Tagent.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tagent.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tagent attached = Tagent.findTagent(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tagent.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tagent.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tagent Tagent.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tagent merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tagent.entityManager() {
        EntityManager em = new Tagent().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tagent.countTagents() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tagent o", Long.class).getSingleResult();
    }
    
    public static List<Tagent> Tagent.findAllTagents() {
        return entityManager().createQuery("SELECT o FROM Tagent o", Tagent.class).getResultList();
    }
    
    public static Tagent Tagent.findTagent(Long id) {
        if (id == null) return null;
        return entityManager().find(Tagent.class, id);
    }
    
    public static List<Tagent> Tagent.findTagentEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tagent o", Tagent.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
