// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import java.lang.String;

privileged aspect Tagent_Roo_ToString {
    
    public String Tagent.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("AgentId: ").append(getAgentId()).append(", ");
        sb.append("CreateTime: ").append(getCreateTime()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Level: ").append(getLevel()).append(", ");
        sb.append("State: ").append(getState()).append(", ");
        sb.append("Userno: ").append(getUserno());
        return sb.toString();
    }
    
}
