// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import com.ruyicai.actioncenter.domain.TcommisionRatio;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect TcommisionRatio_Roo_Json {
    
    public String TcommisionRatio.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static TcommisionRatio TcommisionRatio.fromJsonToTcommisionRatio(String json) {
        return new JSONDeserializer<TcommisionRatio>().use(null, TcommisionRatio.class).deserialize(json);
    }
    
    public static String TcommisionRatio.toJsonArray(Collection<TcommisionRatio> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<TcommisionRatio> TcommisionRatio.fromJsonArrayToTcommisionRatios(String json) {
        return new JSONDeserializer<List<TcommisionRatio>>().use(null, ArrayList.class).use("values", TcommisionRatio.class).deserialize(json);
    }
    
}
