// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import com.ruyicai.actioncenter.domain.TcommisionRatio;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TcommisionRatio_Roo_Entity {
    
    declare @type: TcommisionRatio: @Entity;
    
    declare @type: TcommisionRatio: @Table(name = "TCOMMISIONRATIO");
    
    @PersistenceContext
    transient EntityManager TcommisionRatio.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long TcommisionRatio.id;
    
    public Long TcommisionRatio.getId() {
        return this.id;
    }
    
    public void TcommisionRatio.setId(Long id) {
        this.id = id;
    }
    
    @Transactional
    public void TcommisionRatio.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void TcommisionRatio.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            TcommisionRatio attached = TcommisionRatio.findTcommisionRatio(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void TcommisionRatio.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void TcommisionRatio.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public TcommisionRatio TcommisionRatio.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        TcommisionRatio merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager TcommisionRatio.entityManager() {
        EntityManager em = new TcommisionRatio().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long TcommisionRatio.countTcommisionRatios() {
        return entityManager().createQuery("SELECT COUNT(o) FROM TcommisionRatio o", Long.class).getSingleResult();
    }
    
    public static List<TcommisionRatio> TcommisionRatio.findAllTcommisionRatios() {
        return entityManager().createQuery("SELECT o FROM TcommisionRatio o", TcommisionRatio.class).getResultList();
    }
    
    public static TcommisionRatio TcommisionRatio.findTcommisionRatio(Long id) {
        if (id == null) return null;
        return entityManager().find(TcommisionRatio.class, id);
    }
    
    public static List<TcommisionRatio> TcommisionRatio.findTcommisionRatioEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM TcommisionRatio o", TcommisionRatio.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
