// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import java.lang.Integer;
import java.lang.String;
import java.math.BigDecimal;

privileged aspect TcommisionRatio_Roo_JavaBean {
    
    public String TcommisionRatio.getUserno() {
        return this.userno;
    }
    
    public void TcommisionRatio.setUserno(String userno) {
        this.userno = userno;
    }
    
    public String TcommisionRatio.getLotno() {
        return this.lotno;
    }
    
    public void TcommisionRatio.setLotno(String lotno) {
        this.lotno = lotno;
    }
    
    public BigDecimal TcommisionRatio.getCommisionRatio() {
        return this.commisionRatio;
    }
    
    public void TcommisionRatio.setCommisionRatio(BigDecimal commisionRatio) {
        this.commisionRatio = commisionRatio;
    }
    
    public Integer TcommisionRatio.getCommisionType() {
        return this.commisionType;
    }
    
    public void TcommisionRatio.setCommisionType(Integer commisionType) {
        this.commisionType = commisionType;
    }
    
}
