// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import com.ruyicai.actioncenter.domain.Tuseraction;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tuseraction_Roo_Entity {
    
    declare @type: Tuseraction: @Entity;
    
    declare @type: Tuseraction: @Table(name = "TUSERACTION");
    
    @PersistenceContext
    transient EntityManager Tuseraction.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Tuseraction.id;
    
    public Long Tuseraction.getId() {
        return this.id;
    }
    
    public void Tuseraction.setId(Long id) {
        this.id = id;
    }
    
    @Transactional
    public void Tuseraction.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tuseraction.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tuseraction attached = Tuseraction.findTuseraction(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tuseraction.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tuseraction.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tuseraction Tuseraction.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tuseraction merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tuseraction.entityManager() {
        EntityManager em = new Tuseraction().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tuseraction.countTuseractions() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tuseraction o", Long.class).getSingleResult();
    }
    
    public static List<Tuseraction> Tuseraction.findAllTuseractions() {
        return entityManager().createQuery("SELECT o FROM Tuseraction o", Tuseraction.class).getResultList();
    }
    
    public static Tuseraction Tuseraction.findTuseraction(Long id) {
        if (id == null) return null;
        return entityManager().find(Tuseraction.class, id);
    }
    
    public static List<Tuseraction> Tuseraction.findTuseractionEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tuseraction o", Tuseraction.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
