// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import java.lang.Object;
import java.lang.String;
import javax.persistence.Embeddable;

privileged aspect VipUserPK_Roo_Identifier {
    
    declare @type: VipUserPK: @Embeddable;
    
    public VipUserPK.new(String userno, String yearAndMonth) {
        super();
        this.userno = userno;
        this.yearAndMonth = yearAndMonth;
    }

    private VipUserPK.new() {
        super();
    }

    public String VipUserPK.getUserno() {
        return this.userno;
    }
    
    public String VipUserPK.getYearAndMonth() {
        return this.yearAndMonth;
    }
    
    public boolean VipUserPK.equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (!(obj instanceof VipUserPK)) return false;
        VipUserPK other = (VipUserPK) obj;
        if (userno == null) {
            if (other.userno != null) return false;
        } else if (!userno.equals(other.userno)) return false;
        if (yearAndMonth == null) {
            if (other.yearAndMonth != null) return false;
        } else if (!yearAndMonth.equals(other.yearAndMonth)) return false;
        return true;
    }
    
    public int VipUserPK.hashCode() {
        final int prime = 31;
        int result = 17;
        result = prime * result + (userno == null ? 0 : userno.hashCode());
        result = prime * result + (yearAndMonth == null ? 0 : yearAndMonth.hashCode());
        return result;
    }
    
}
