// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import com.ruyicai.actioncenter.domain.VipUser;
import com.ruyicai.actioncenter.domain.VipUserPK;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VipUser_Roo_Entity {
    
    declare @type: VipUser: @Entity;
    
    declare @type: VipUser: @Table(name = "VipUser");
    
    @PersistenceContext
    transient EntityManager VipUser.entityManager;
    
    @Transactional
    public void VipUser.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void VipUser.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            VipUser attached = VipUser.findVipUser(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void VipUser.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void VipUser.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public VipUser VipUser.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        VipUser merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager VipUser.entityManager() {
        EntityManager em = new VipUser().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long VipUser.countVipUsers() {
        return entityManager().createQuery("SELECT COUNT(o) FROM VipUser o", Long.class).getSingleResult();
    }
    
    public static List<VipUser> VipUser.findAllVipUsers() {
        return entityManager().createQuery("SELECT o FROM VipUser o", VipUser.class).getResultList();
    }
    
    public static VipUser VipUser.findVipUser(VipUserPK id) {
        if (id == null) return null;
        return entityManager().find(VipUser.class, id);
    }
    
    public static List<VipUser> VipUser.findVipUserEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM VipUser o", VipUser.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
