// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import java.lang.String;

privileged aspect VipUserPK_Roo_ToString {
    
    public String VipUserPK.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Userno: ").append(getUserno()).append(", ");
        sb.append("YearAndMonth: ").append(getYearAndMonth());
        return sb.toString();
    }
    
}
