// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import java.lang.String;

privileged aspect VipUser_Roo_ToString {
    
    public String VipUser.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Buyamt: ").append(getBuyamt()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("ModifyTime: ").append(getModifyTime());
        return sb.toString();
    }
    
}
