// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import java.io.Serializable;

privileged aspect SSCPrizedDetailPK_Roo_Serializable {
    
    declare parents: SSCPrizedDetailPK implements Serializable;
    
}
