// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import com.ruyicai.actioncenter.domain.Tagent;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Tagent_Roo_Json {
    
    public String Tagent.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static Tagent Tagent.fromJsonToTagent(String json) {
        return new JSONDeserializer<Tagent>().use(null, Tagent.class).deserialize(json);
    }
    
    public static String Tagent.toJsonArray(Collection<Tagent> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<Tagent> Tagent.fromJsonArrayToTagents(String json) {
        return new JSONDeserializer<List<Tagent>>().use(null, ArrayList.class).use("values", Tagent.class).deserialize(json);
    }
    
}
