// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Date;

privileged aspect Tagent_Roo_JavaBean {
    
    public String Tagent.getUserno() {
        return this.userno;
    }
    
    public void Tagent.setUserno(String userno) {
        this.userno = userno;
    }
    
    public Date Tagent.getCreateTime() {
        return this.createTime;
    }
    
    public void Tagent.setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    public Integer Tagent.getState() {
        return this.state;
    }
    
    public void Tagent.setState(Integer state) {
        this.state = state;
    }
    
    public Long Tagent.getAgentId() {
        return this.agentId;
    }
    
    public void Tagent.setAgentId(Long agentId) {
        this.agentId = agentId;
    }
    
    public Integer Tagent.getLevel() {
        return this.level;
    }
    
    public void Tagent.setLevel(Integer level) {
        this.level = level;
    }
    
}
