// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.actioncenter.domain;

import java.lang.String;

privileged aspect WorldCupBigUser_Roo_JavaBean {
    
    public String WorldCupBigUser.getUserno() {
        return this.userno;
    }
    
    public void WorldCupBigUser.setUserno(String userno) {
        this.userno = userno;
    }
    
}
