// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.lottery.domain;

import java.lang.Long;
import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect Tuserachievement_Roo_JavaBean {
    
    public Long Tuserachievement.getId() {
        return this.id;
    }
    
    public void Tuserachievement.setId(Long id) {
        this.id = id;
    }
    
    public String Tuserachievement.getUserno() {
        return this.userno;
    }
    
    public void Tuserachievement.setUserno(String userno) {
        this.userno = userno;
    }
    
    public String Tuserachievement.getLotno() {
        return this.lotno;
    }
    
    public void Tuserachievement.setLotno(String lotno) {
        this.lotno = lotno;
    }
    
    public BigDecimal Tuserachievement.getEffectiveAchievement() {
        return this.effectiveAchievement;
    }
    
    public void Tuserachievement.setEffectiveAchievement(BigDecimal effectiveAchievement) {
        this.effectiveAchievement = effectiveAchievement;
    }
    
    public BigDecimal Tuserachievement.getIneffectiveAchievement() {
        return this.ineffectiveAchievement;
    }
    
    public void Tuserachievement.setIneffectiveAchievement(BigDecimal ineffectiveAchievement) {
        this.ineffectiveAchievement = ineffectiveAchievement;
    }
    
    public Date Tuserachievement.getLastModifyTime() {
        return this.lastModifyTime;
    }
    
    public void Tuserachievement.setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
    
}
