// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.lottery.domain;

import java.lang.String;

privileged aspect Tuserachievement_Roo_ToString {
    
    public String Tuserachievement.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("EffectiveAchievement: ").append(getEffectiveAchievement()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("IneffectiveAchievement: ").append(getIneffectiveAchievement()).append(", ");
        sb.append("LastModifyTime: ").append(getLastModifyTime()).append(", ");
        sb.append("Lotno: ").append(getLotno()).append(", ");
        sb.append("Userno: ").append(getUserno());
        return sb.toString();
    }
    
}
